config/routes.rb
Bikeways::Application.routes.draw do
  #devise_for :users, :controllers => {:registrations => "registrations"}
  #resources :users

  root :to => "segments#index"
  resources :segments
end

app/models/segment.rb
require 'gis_tools'

class Segment < ActiveRecord::Base

  scope :bikeway_type, ->(type) { where("bikeway_type = ?", type) }
  scope :full_street_name, ->(name) { where("full_street_name = ?", name) }

  def self.total_length_km
    (Segment.sum(:length_m)/1024).round(2)
  end

  def kml
    result = Segment.select('*, st_askml(st_transform(geom, 4326)) as _kml').where(:id => self.id).first
    result._kml
  end

  # XXX: this is view level stuff, move it to a helper or something
  # certainly not in the model.
  def style_id
    STYLE_ID_CODES[self.bikeway_type]
  end

  def name_with_range
    "#{range} #{full_street_name}"
  end

  def description
    "#{name_with_range} (#{bikeway_type}, #{length_m.round(1)} m)"
  end

  def to_s
    description
  end

  def range
    max = [highest_address_left, highest_address_right].reject { |n| nil_or_zero?(n) }.max
    min = [lowest_address_left, lowest_address_right].reject { |n| nil_or_zero?(n)  }.min

    if nil_or_zero?(min) && nil_or_zero?(max)
      nil
    else
      "#{min}-#{max}"
    end
  end

  private
  def nil_or_zero?(n)
    n.nil? || n == 0
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/segments_controller.rb
require 'segments_datatable'

class SegmentsController < ApplicationController
  has_scope :bikeway_type
  has_scope :full_street_name

  def index
    @segments = apply_scopes(Segment).all
    @kml_url = url_for current_scopes.merge(:controller => :segments, :action => :index, :format => :kml)
    @json_url = url_for current_scopes.merge(:controller => :segments, :action => :index, :format => :json)

    respond_to do |format|
      format.html  # index.html.haml
      format.json {
        render json: SegmentsDatatable.new(view_context, @segments)
      }
      format.kml {
        render template: 'shared/kml'
      }
    end
  end

  def show
    raise 'oops'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikeways/kml.erb
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
  <%= render 'shared/kml_styles' %>

  <% @bikeway.bikeway_segments.each do |segment| %>
    <Placemark>
      <name><%= segment.id %></name>
      <styleUrl>#<%= segment.style_id %></styleUrl>
      <%= raw segment.kml %>
    </Placemark>
  <% end %>
</Document>
</kml>

app/views/home/index.html.haml
%h3 Bikeways

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        -# render 'layouts/navigation_links'
        %li= link_to 'Segments', segments_path

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Bikeways'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Bikeways'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{data: { controller: controller_name, action: action_name }}
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/segments/index.html.haml
%h3 Bikeway Segments

= render :partial => 'shared/segments', :locals => { :segments => @segments }

%table#segments.table.table-hover{ data: { source: @json_url }}
  %thead
    %tr
      %th id
      %th full_street_name
      %th lowest_address_left
      %th lowest_address_right
      %th highest_address_left
      %th highest_address_right
      %th bikeway_type
      %th length_m
  %tbody

app/views/segments/show.html.haml
%h3= "Segment: #{@segments.first.id}"

= render :partial => 'shared/segments', :locals => { :segments => @segments }

app/views/shared/_kml_styles.erb
<Style id="suggestedConnections">
  <LineStyle><color>FF2884F4</color><width>4</width></LineStyle>
</Style>
<Style id="sharrows">
  <LineStyle><color>FF6B64ED64</color><width>4</width></LineStyle>
</Style>
<Style id="signedRoutes">
  <LineStyle><color>FFBC7747</color><width>8</width></LineStyle>
</Style>
<Style id="cycleTracks">
  <LineStyle><color>FF3E811281</color><width>8</width></LineStyle>
</Style>
<Style id="contraFlow">
  <LineStyle><color>FFA86B69</color><width>6</width></LineStyle>
</Style>
<Style id="suggestedOnStreet">
  <LineStyle><color>FFBC7747</color><width>4</width></LineStyle>
</Style>
<Style id="minorMultiUse">
  <LineStyle><color>FF8A3655</color><width>4</width></LineStyle>
</Style>
<Style id="parkRoads">
  <LineStyle><color>FF898785</color><width>8</width></LineStyle>
</Style>
<Style id="majorMultiUse">
  <LineStyle><color>FF8A3655</color><width>8</width></LineStyle>
</Style>
<Style id="bikeLanes">
  <LineStyle><color>FF2E21C7</color><width>8</width></LineStyle>
</Style>
<Style id="informalDirtFootpath">
  <LineStyle><color>FF3E8112</color><width>8</width></LineStyle>
</Style>

app/views/shared/_segments.haml
.row
  .col-xs-12
    .google-map-canvas
      #map{data: { kml_url: @kml_url }}

/ .row
/   .col-xs-12
/     %table.table
/       %thead
/         %th id
/         %th full_street_name
/         %th lowest_address_left
/         %th lowest_address_right
/         %th highest_address_left
/         %th highest_address_right
/         %th bikeway_type
/         %th length_m
/       %tbody
/       - segments.each do |segment|
/         %tr
/           %td= link_to segment.id, segment
/           %td= segment.full_street_name
/           %td= segment.lowest_address_left
/           %td= segment.lowest_address_right
/           %td= segment.highest_address_left
/           %td= segment.highest_address_right
/           %td= segment.bikeway_type
/           %td= segment.length_m

%script{src: '//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry'}
%script{src: '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'}

app/views/shared/kml.erb
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
  <%= render 'shared/kml_styles' %>

  <% @segments.each do |segment| %>
    <Placemark>
      <name><%= segment.to_s %></name>
      <styleUrl>#<%= segment.style_id %></styleUrl>
      <%= raw segment.kml %>
    </Placemark>
  <% end %>
</Document>
</kml>

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}
= link_to 'Edit account', edit_user_path